/Users/dp/Desktop/project/github/opentrons/venv/lib/python3.10/site-packages/opentrons/hardware_control/simulator_setup.py:205: UserWarning: Simulator configuration does not name a machine, defaulting to OT-2 Standard
  warn(
/Users/dp/.opentrons/robot_settings.json not found. Loading defaults
Deck calibration not found.
/Users/dp/.opentrons/deck_calibration.json not found. Loading defaults
Picking up tip from A1 of 10uL Tips on 1
Transferring 8.0 from A1 of 12-Channel Trough on 2 to A1 of 384-Well Plate on 3
	Aspirating 8.0 uL from A1 of 12-Channel Trough on 2 at 5.0 uL/sec
	Dispensing 8.0 uL into A1 of 384-Well Plate on 3 at 10.0 uL/sec
Dropping tip into A1 of Opentrons Fixed Trash on 12
Picking up tip from A1 of 50uL Tips on 4
Transferring 15.0 from A2 of 12-Channel Trough on 2 to A1 of 384-Well Plate on 3
	Aspirating 15.0 uL from A2 of 12-Channel Trough on 2 at 25.0 uL/sec
	Dispensing 15.0 uL into A1 of 384-Well Plate on 3 at 50.0 uL/sec
Mixing 5 times with a volume of 45.0 ul
	Aspirating 45.0 uL from A1 of 384-Well Plate on 3 at 25.0 uL/sec
	Dispensing 45.0 uL into A1 of 384-Well Plate on 3 at 50.0 uL/sec
	Aspirating 45.0 uL from A1 of 384-Well Plate on 3 at 25.0 uL/sec
	Dispensing 45.0 uL into A1 of 384-Well Plate on 3 at 50.0 uL/sec
	Aspirating 45.0 uL from A1 of 384-Well Plate on 3 at 25.0 uL/sec
	Dispensing 45.0 uL into A1 of 384-Well Plate on 3 at 50.0 uL/sec
	Aspirating 45.0 uL from A1 of 384-Well Plate on 3 at 25.0 uL/sec
	Dispensing 45.0 uL into A1 of 384-Well Plate on 3 at 50.0 uL/sec
	Aspirating 45.0 uL from A1 of 384-Well Plate on 3 at 25.0 uL/sec
	Dispensing 45.0 uL into A1 of 384-Well Plate on 3 at 50.0 uL/sec
Dropping tip into A1 of Opentrons Fixed Trash on 12
Caught exception: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-4' coro=<Poller._poll_forever() running at /Users/dp/Desktop/project/github/opentrons/venv/lib/python3.10/site-packages/opentrons/hardware_control/poller.py:80> wait_for=<Future pending cb=[Task.task_wakeup()]>>}
Caught exception: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-3' coro=<Poller._poll_forever() running at /Users/dp/Desktop/project/github/opentrons/venv/lib/python3.10/site-packages/opentrons/hardware_control/poller.py:80> wait_for=<Future pending cb=[Task.task_wakeup()]>>}
Caught exception: {'message': 'Task was destroyed but it is pending!', 'task': <Task pending name='Task-2' coro=<Poller._poll_forever() running at /Users/dp/Desktop/project/github/opentrons/venv/lib/python3.10/site-packages/opentrons/hardware_control/poller.py:80> wait_for=<Future pending cb=[Task.task_wakeup()]>>}
